
### GET Users
GET http://localhost:5000/api/users/list


### GET Users
GET http://localhost:5000/api/users

### GET User
GET http://localhost:5000/api/users/64aef5ed21d609b8278fb8b8

### POST User
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstName" : "Vijayalaxmy", 
    "lastName" : "Kanakaratname", 
    "email" : "vijaya@gmail.com",
    "username" : "vijaya", 
    "password" : "test1234", 
    "phone" : 77, 
    "address" : "Vavuniya"
}

### PUT User
PUT http://localhost:5000/api/users/64aef5ed21d609b8278fb8b8
Content-Type: application/json

{
    "firstName" : "subhoshini", 
    "lastName" : "shi", 
    "email" : "subosi@gmail.com",
    "username" : "subhos", 
    "password" : "test1234", 
    "phone" : 77, 
    "address" : "Vavuniya"
}

### DELETE User
DELETE http://localhost:5000/api/users/64aef5ed21d609b8278fb8b8
Content-Type: application/json

